/* ================================================================
   indice.js — índice de páginas da TriânguloLeaks, usado pela busca
   (busca.js) e pela detecção de duplicatas (duplicatas.js).
   Definido como variável global porque fetch() de um JSON local
   falha ao abrir os arquivos diretamente com file://.

   Cada item pode ter, além de slug/titulo/href/resumo/categorias/tipo:
     local          {string}   cidade/região a que o artigo se refere
     pessoa         {nome, sobrenome, sexo?, localNascimento?,
                      localFalecimento?, nomePai?, nomeMae?, conjuge?}
                    só em biografias — os campos genealógicos
                    (localNascimento/localFalecimento/nomePai/nomeMae/
                    conjuge) seguem o mesmo tipo de dado usado por
                    ferramentas de genealogia como FamilySearch/Family
                    Tree (pessoa + eventos de vida com local + parentes
                    diretos), usados pelos filtros de genealogia da
                    busca avançada (ver busca.html/js/busca.js)
     anoInicio/anoFim {number} intervalo de datas do assunto do artigo
                     (nascimento–morte, fundação–hoje, etc.), usado
                     pelo filtro "Datas" da busca avançada — em uma
                     biografia, anoInicio = ano de nascimento e
                     anoFim = ano de falecimento (ou null se vivo)
     palavrasChave  {string[]} termos adicionais para correlacionar
                     este artigo com outros nos filtros de busca
   Nenhum desses campos é obrigatório: a busca simples (por título e
   resumo) continua funcionando para itens sem eles.
   ================================================================
   ÍNDICE DO ARQUIVO (gerado/mantido em lote)
     1. window.TP_INDICE  → array estático com 1 objeto por página
        indexada (artigo/categoria/especial), consumido por
        js/busca.js, js/duplicatas.js, js/estatisticas.js,
        js/linha-do-tempo.js, js/contador-home.js e pelos scripts
        Python que regeneram especial-todas-as-paginas.html e as
        categoria-*.html a partir deste arquivo (ver
        ESTRUTURA-DO-PROJETO.md).
     2. IIFE de autoindexação (final do arquivo) → funde, em tempo de
        carregamento, o índice estático acima com o índice local
        (localStorage "tp:indice-local", alimentado por
        TP.indexarArtigo em js/estado.js) — nenhuma função nomeada,
        roda imediatamente ao carregar a tag <script>.
   ================================================================ */
window.TP_INDICE = [
  { slug: "triangulo-mineiro", titulo: "Triângulo Mineiro", href: "artigo-triangulo-mineiro.html",
    resumo: "Região de Minas Gerais entre os rios Grande e Paranaíba, com forte vocação agropecuária.",
    categorias: ["Geografia", "História"], tipo: "artigo",
    local: "Triângulo Mineiro, Minas Gerais",
    palavrasChave: ["Minas Gerais", "Alto Paranaíba", "Cerrado", "pecuária", "agropecuária"] },
  { slug: "uberlandia", titulo: "Uberlândia", href: "artigo-uberlandia.html",
    resumo: "Município do Triângulo Mineiro, polo logístico, industrial e universitário.",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Uberlândia, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1888, anoFim: null,
    palavrasChave: ["logística", "UFU", "polo industrial"] },
  { slug: "uberaba", titulo: "Uberaba", href: "artigo-uberaba.html",
    resumo: "Município referência nacional em pecuária zebuína, sede da ExpoZebu.",
    categorias: ["Cidades", "Economia"], tipo: "artigo",
    local: "Uberaba, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1811, anoFim: null,
    palavrasChave: ["zebu", "ExpoZebu", "paleontologia", "ferrovia Mogiana"] },
  { slug: "araxa", titulo: "Araxá", href: "artigo-araxa.html",
    resumo: "Município conhecido por suas águas termais e mineração.",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Araxá, Triângulo Mineiro, Minas Gerais",
    palavrasChave: ["águas termais", "mineração", "nióbio"] },
  { slug: "frutal", titulo: "Frutal", href: "artigo-frutal.html",
    resumo: "Município do Triângulo Mineiro, próximo ao rio Grande.",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Frutal, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1887, anoFim: null,
    palavrasChave: ["rio Grande"] },
  { slug: "ituiutaba", titulo: "Ituiutaba", href: "artigo-ituiutaba.html",
    resumo: "Município da região do Pontal, com forte atividade agrícola.",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Ituiutaba, Pontal do Triângulo Mineiro, Minas Gerais",
    anoInicio: 1901, anoFim: null,
    palavrasChave: ["Pontal", "agricultura"] },
  { slug: "sacramento-mg", titulo: "Sacramento (MG)", href: "artigo-sacramento-mg.html",
    resumo: "Município histórico ligado à trajetória do Barão da Rifaina.",
    categorias: ["Cidades", "História"], tipo: "artigo",
    local: "Sacramento, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1870, anoFim: null,
    palavrasChave: ["Barão da Rifaina", "Vicente de Paula Vieira"] },
  { slug: "rio-paranaiba", titulo: "Rio Paranaíba", href: "artigo-rio-paranaiba.html",
    resumo: "Um dos limites naturais do Triângulo Mineiro.",
    categorias: ["Geografia"], tipo: "artigo",
    local: "Triângulo Mineiro, Minas Gerais",
    palavrasChave: ["hidrografia", "limite natural"] },
  { slug: "peiropolis", titulo: "Peirópolis", href: "artigo-peiropolis.html",
    resumo: "Distrito de Uberaba, importante sítio paleontológico.",
    categorias: ["Geografia", "Cultura"], tipo: "artigo",
    local: "Peirópolis, Uberaba, Triângulo Mineiro, Minas Gerais",
    palavrasChave: ["paleontologia", "dinossauros", "Uberaba"] },
  { slug: "zebu-e-a-expozebu", titulo: "Zebu e a ExpoZebu", href: "artigo-zebu-e-a-expozebu.html",
    resumo: "Raça bovina e feira agropecuária de referência nacional em Uberaba.",
    categorias: ["Economia", "Cultura"], tipo: "artigo",
    local: "Uberaba, Triângulo Mineiro, Minas Gerais",
    palavrasChave: ["zebu", "ExpoZebu", "pecuária"] },
  { slug: "cerrado", titulo: "Cerrado", href: "artigo-cerrado.html",
    resumo: "Bioma predominante no Triângulo Mineiro.",
    categorias: ["Meio ambiente"], tipo: "artigo",
    local: "Triângulo Mineiro, Minas Gerais",
    palavrasChave: ["bioma", "meio ambiente"] },
  { slug: "pao-de-queijo", titulo: "Pão de queijo", href: "artigo-pao-de-queijo.html",
    resumo: "Iguaria típica da culinária mineira.",
    categorias: ["Gastronomia"], tipo: "artigo",
    local: "Minas Gerais",
    palavrasChave: ["culinária", "gastronomia mineira"] },
  { slug: "vicente-de-paula-vieira", titulo: "Vicente de Paula Vieira (Barão da Rifaina)", href: "artigo-vicente-de-paula-vieira.html",
    resumo: "Figura histórica (1833–1895) ligada a Sacramento (MG) e ao Triângulo Mineiro.",
    categorias: ["História", "Pessoas"], tipo: "artigo",
    local: "Sacramento, Triângulo Mineiro, Minas Gerais",
    pessoa: {
      nome: "Vicente", sobrenome: "de Paula Vieira",
      sexo: "M",
      localNascimento: "Queluz de Minas (atual Conselheiro Lafaiete), Minas Gerais",
      localFalecimento: "Sacramento, Minas Gerais",
      nomePai: "Severino José Vieira",
      nomeMae: "Maria Antônia de Lima",
      conjuge: "Maria José da Conceição"
    },
    anoInicio: 1833, anoFim: 1895,
    palavrasChave: ["Barão da Rifaina", "título nobiliárquico", "Sacramento", "genealogia", "Queluz de Minas", "Conselheiro Lafaiete"] },
  { slug: "campos-altos", titulo: "Campos Altos", href: "artigo-campos-altos.html",
    resumo: "Município da microrregião de Araxá, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Campos Altos, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1943, anoFim: null,
    palavrasChave: ["Araxá", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "ibia", titulo: "Ibiá", href: "artigo-ibia.html",
    resumo: "Município da microrregião de Araxá, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Ibiá, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1923, anoFim: null,
    palavrasChave: ["Araxá", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "nova-ponte", titulo: "Nova Ponte", href: "artigo-nova-ponte.html",
    resumo: "Município da microrregião de Araxá, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Nova Ponte, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1938, anoFim: null,
    palavrasChave: ["Araxá", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "pedrinopolis", titulo: "Pedrinópolis", href: "artigo-pedrinopolis.html",
    resumo: "Município da microrregião de Araxá, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Pedrinópolis, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1963, anoFim: null,
    palavrasChave: ["Araxá", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "perdizes", titulo: "Perdizes", href: "artigo-perdizes.html",
    resumo: "Município da microrregião de Araxá, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Perdizes, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1938, anoFim: null,
    palavrasChave: ["Araxá", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "pratinha", titulo: "Pratinha", href: "artigo-pratinha.html",
    resumo: "Município da microrregião de Araxá, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Pratinha, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1948, anoFim: null,
    palavrasChave: ["Araxá", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "santa-juliana", titulo: "Santa Juliana", href: "artigo-santa-juliana.html",
    resumo: "Município da microrregião de Araxá, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Santa Juliana, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1938, anoFim: null,
    palavrasChave: ["Araxá", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "tapira", titulo: "Tapira", href: "artigo-tapira.html",
    resumo: "Município da microrregião de Araxá, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Tapira, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1962, anoFim: null,
    palavrasChave: ["Araxá", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "campina-verde", titulo: "Campina Verde", href: "artigo-campina-verde.html",
    resumo: "Município da microrregião de Frutal, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Campina Verde, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1938, anoFim: null,
    palavrasChave: ["Frutal", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "carneirinho", titulo: "Carneirinho", href: "artigo-carneirinho.html",
    resumo: "Município da microrregião de Frutal, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Carneirinho, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1992, anoFim: null,
    palavrasChave: ["Frutal", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "comendador-gomes", titulo: "Comendador Gomes", href: "artigo-comendador-gomes.html",
    resumo: "Município da microrregião de Frutal, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Comendador Gomes, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1948, anoFim: null,
    palavrasChave: ["Frutal", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "fronteira", titulo: "Fronteira", href: "artigo-fronteira.html",
    resumo: "Município da microrregião de Frutal, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Fronteira, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1962, anoFim: null,
    palavrasChave: ["Frutal", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "itapagipe", titulo: "Itapagipe", href: "artigo-itapagipe.html",
    resumo: "Município da microrregião de Frutal, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Itapagipe, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1948, anoFim: null,
    palavrasChave: ["Frutal", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "iturama", titulo: "Iturama", href: "artigo-iturama.html",
    resumo: "Município da microrregião de Frutal, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Iturama, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1949, anoFim: null,
    palavrasChave: ["Frutal", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "limeira-do-oeste", titulo: "Limeira do Oeste", href: "artigo-limeira-do-oeste.html",
    resumo: "Município da microrregião de Frutal, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Limeira do Oeste, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1992, anoFim: null,
    palavrasChave: ["Frutal", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "pirajuba", titulo: "Pirajuba", href: "artigo-pirajuba.html",
    resumo: "Município da microrregião de Frutal, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Pirajuba, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1953, anoFim: null,
    palavrasChave: ["Frutal", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "planura", titulo: "Planura", href: "artigo-planura.html",
    resumo: "Município da microrregião de Frutal, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Planura, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1962, anoFim: null,
    palavrasChave: ["Frutal", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "sao-francisco-de-sales", titulo: "São Francisco de Sales", href: "artigo-sao-francisco-de-sales.html",
    resumo: "Município da microrregião de Frutal, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "São Francisco de Sales, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1962, anoFim: null,
    palavrasChave: ["Frutal", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "uniao-de-minas", titulo: "União de Minas", href: "artigo-uniao-de-minas.html",
    resumo: "Município da microrregião de Frutal, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "União de Minas, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1995, anoFim: null,
    palavrasChave: ["Frutal", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "cachoeira-dourada", titulo: "Cachoeira Dourada", href: "artigo-cachoeira-dourada.html",
    resumo: "Município da microrregião de Ituiutaba, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Cachoeira Dourada, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1962, anoFim: null,
    palavrasChave: ["Ituiutaba", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "capinopolis", titulo: "Capinópolis", href: "artigo-capinopolis.html",
    resumo: "Município da microrregião de Ituiutaba, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Capinópolis, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1953, anoFim: null,
    palavrasChave: ["Ituiutaba", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "gurinhata", titulo: "Gurinhatã", href: "artigo-gurinhata.html",
    resumo: "Município da microrregião de Ituiutaba, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Gurinhatã, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1962, anoFim: null,
    palavrasChave: ["Ituiutaba", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "ipiacu", titulo: "Ipiaçu", href: "artigo-ipiacu.html",
    resumo: "Município da microrregião de Ituiutaba, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Ipiaçu, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1962, anoFim: null,
    palavrasChave: ["Ituiutaba", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "santa-vitoria", titulo: "Santa Vitória", href: "artigo-santa-vitoria.html",
    resumo: "Município da microrregião de Ituiutaba, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Santa Vitória, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1948, anoFim: null,
    palavrasChave: ["Ituiutaba", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "arapua", titulo: "Arapuá", href: "artigo-arapua.html",
    resumo: "Município da microrregião de Patos de Minas, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Arapuá, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1962, anoFim: null,
    palavrasChave: ["Patos de Minas", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "carmo-do-paranaiba", titulo: "Carmo do Paranaíba", href: "artigo-carmo-do-paranaiba.html",
    resumo: "Município da microrregião de Patos de Minas, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Carmo do Paranaíba, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1887, anoFim: null,
    palavrasChave: ["Patos de Minas", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "guimarania", titulo: "Guimarânia", href: "artigo-guimarania.html",
    resumo: "Município da microrregião de Patos de Minas, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Guimarânia, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1962, anoFim: null,
    palavrasChave: ["Patos de Minas", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "lagoa-formosa", titulo: "Lagoa Formosa", href: "artigo-lagoa-formosa.html",
    resumo: "Município da microrregião de Patos de Minas, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Lagoa Formosa, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1962, anoFim: null,
    palavrasChave: ["Patos de Minas", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "matutina", titulo: "Matutina", href: "artigo-matutina.html",
    resumo: "Município da microrregião de Patos de Minas, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Matutina, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1953, anoFim: null,
    palavrasChave: ["Patos de Minas", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "patos-de-minas", titulo: "Patos de Minas", href: "artigo-patos-de-minas.html",
    resumo: "Município da microrregião de Patos de Minas, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Patos de Minas, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1892, anoFim: null,
    palavrasChave: ["Patos de Minas", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "rio-paranaiba-mg", titulo: "Rio Paranaíba", href: "artigo-rio-paranaiba-mg.html",
    resumo: "Município da microrregião de Patos de Minas, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Rio Paranaíba, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1911, anoFim: null,
    palavrasChave: ["Patos de Minas", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "santa-rosa-da-serra", titulo: "Santa Rosa da Serra", href: "artigo-santa-rosa-da-serra.html",
    resumo: "Município da microrregião de Patos de Minas, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Santa Rosa da Serra, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1962, anoFim: null,
    palavrasChave: ["Patos de Minas", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "sao-gotardo", titulo: "São Gotardo", href: "artigo-sao-gotardo.html",
    resumo: "Município da microrregião de Patos de Minas, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "São Gotardo, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1915, anoFim: null,
    palavrasChave: ["Patos de Minas", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "tiros", titulo: "Tiros", href: "artigo-tiros.html",
    resumo: "Município da microrregião de Patos de Minas, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Tiros, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1923, anoFim: null,
    palavrasChave: ["Patos de Minas", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "abadia-dos-dourados", titulo: "Abadia dos Dourados", href: "artigo-abadia-dos-dourados.html",
    resumo: "Município da microrregião de Patrocínio, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Abadia dos Dourados, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1948, anoFim: null,
    palavrasChave: ["Patrocínio", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "coromandel", titulo: "Coromandel", href: "artigo-coromandel.html",
    resumo: "Município da microrregião de Patrocínio, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Coromandel, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1923, anoFim: null,
    palavrasChave: ["Patrocínio", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "cruzeiro-da-fortaleza", titulo: "Cruzeiro da Fortaleza", href: "artigo-cruzeiro-da-fortaleza.html",
    resumo: "Município da microrregião de Patrocínio, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Cruzeiro da Fortaleza, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1962, anoFim: null,
    palavrasChave: ["Patrocínio", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "douradoquara", titulo: "Douradoquara", href: "artigo-douradoquara.html",
    resumo: "Município da microrregião de Patrocínio, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Douradoquara, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1962, anoFim: null,
    palavrasChave: ["Patrocínio", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "estrela-do-sul", titulo: "Estrela do Sul", href: "artigo-estrela-do-sul.html",
    resumo: "Município da microrregião de Patrocínio, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Estrela do Sul, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1861, anoFim: null,
    palavrasChave: ["Patrocínio", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "grupiara", titulo: "Grupiara", href: "artigo-grupiara.html",
    resumo: "Município da microrregião de Patrocínio, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Grupiara, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1962, anoFim: null,
    palavrasChave: ["Patrocínio", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "irai-de-minas", titulo: "Iraí de Minas", href: "artigo-irai-de-minas.html",
    resumo: "Município da microrregião de Patrocínio, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Iraí de Minas, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1962, anoFim: null,
    palavrasChave: ["Patrocínio", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "monte-carmelo", titulo: "Monte Carmelo", href: "artigo-monte-carmelo.html",
    resumo: "Município da microrregião de Patrocínio, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Monte Carmelo, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1892, anoFim: null,
    palavrasChave: ["Patrocínio", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "patrocinio", titulo: "Patrocínio", href: "artigo-patrocinio.html",
    resumo: "Município da microrregião de Patrocínio, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Patrocínio, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1840, anoFim: null,
    palavrasChave: ["Patrocínio", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "romaria", titulo: "Romaria", href: "artigo-romaria.html",
    resumo: "Município da microrregião de Patrocínio, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Romaria, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1962, anoFim: null,
    palavrasChave: ["Patrocínio", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "serra-do-salitre", titulo: "Serra do Salitre", href: "artigo-serra-do-salitre.html",
    resumo: "Município da microrregião de Patrocínio, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Serra do Salitre, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1953, anoFim: null,
    palavrasChave: ["Patrocínio", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "agua-comprida", titulo: "Água Comprida", href: "artigo-agua-comprida.html",
    resumo: "Município da microrregião de Uberaba, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Água Comprida, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1953, anoFim: null,
    palavrasChave: ["Uberaba", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "campo-florido", titulo: "Campo Florido", href: "artigo-campo-florido.html",
    resumo: "Município da microrregião de Uberaba, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Campo Florido, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1938, anoFim: null,
    palavrasChave: ["Uberaba", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "conceicao-das-alagoas", titulo: "Conceição das Alagoas", href: "artigo-conceicao-das-alagoas.html",
    resumo: "Município da microrregião de Uberaba, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Conceição das Alagoas, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1938, anoFim: null,
    palavrasChave: ["Uberaba", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "conquista", titulo: "Conquista", href: "artigo-conquista.html",
    resumo: "Município da microrregião de Uberaba, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Conquista, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1925, anoFim: null,
    palavrasChave: ["Uberaba", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "delta", titulo: "Delta", href: "artigo-delta.html",
    resumo: "Município da microrregião de Uberaba, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Delta, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1995, anoFim: null,
    palavrasChave: ["Uberaba", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "verissimo", titulo: "Veríssimo", href: "artigo-verissimo.html",
    resumo: "Município da microrregião de Uberaba, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Veríssimo, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1938, anoFim: null,
    palavrasChave: ["Uberaba", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "araguari", titulo: "Araguari", href: "artigo-araguari.html",
    resumo: "Município da microrregião de Uberlândia, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Araguari, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1888, anoFim: null,
    palavrasChave: ["Uberlândia", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "arapora", titulo: "Araporã", href: "artigo-arapora.html",
    resumo: "Município da microrregião de Uberlândia, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Araporã, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1992, anoFim: null,
    palavrasChave: ["Uberlândia", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "canapolis", titulo: "Canápolis", href: "artigo-canapolis.html",
    resumo: "Município da microrregião de Uberlândia, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Canápolis, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1948, anoFim: null,
    palavrasChave: ["Uberlândia", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "cascalho-rico", titulo: "Cascalho Rico", href: "artigo-cascalho-rico.html",
    resumo: "Município da microrregião de Uberlândia, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Cascalho Rico, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1948, anoFim: null,
    palavrasChave: ["Uberlândia", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "centralina", titulo: "Centralina", href: "artigo-centralina.html",
    resumo: "Município da microrregião de Uberlândia, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Centralina, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1953, anoFim: null,
    palavrasChave: ["Uberlândia", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "indianopolis", titulo: "Indianópolis", href: "artigo-indianopolis.html",
    resumo: "Município da microrregião de Uberlândia, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Indianópolis, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1938, anoFim: null,
    palavrasChave: ["Uberlândia", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "monte-alegre-de-minas", titulo: "Monte Alegre de Minas", href: "artigo-monte-alegre-de-minas.html",
    resumo: "Município da microrregião de Uberlândia, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Monte Alegre de Minas, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1870, anoFim: null,
    palavrasChave: ["Uberlândia", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "prata", titulo: "Prata", href: "artigo-prata.html",
    resumo: "Município da microrregião de Uberlândia, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Prata, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1873, anoFim: null,
    palavrasChave: ["Uberlândia", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "tupaciguara", titulo: "Tupaciguara", href: "artigo-tupaciguara.html",
    resumo: "Município da microrregião de Uberlândia, Triângulo Mineiro e Alto Paranaíba (esboço).",
    categorias: ["Cidades"], tipo: "artigo",
    local: "Tupaciguara, Triângulo Mineiro, Minas Gerais",
    anoInicio: 1912, anoFim: null,
    palavrasChave: ["Uberlândia", "Triângulo Mineiro e Alto Paranaíba", "esboço"] },
  { slug: "capitao-mor-jose-vieira-da-silva", titulo: "Capitão-Mór José Vieira da Silva", href: "artigo-capitao-mor-jose-vieira-da-silva.html",
    resumo: "Comandante de ordenanças e grande proprietário de terras no sul de Minas Gerais; articulou a migração de mão de obra rural para a expansão do povoamen…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Queluz de Minas (atual Conselheiro Lafaiete), Minas Gerais",
    anoInicio: 1765, anoFim: 1832,
    pessoa: { nome: "José", sobrenome: "Vieira da Silva", sexo: "M", localNascimento: "Queluz de Minas (atual Conselheiro Lafaiete), Minas Gerais", conjuge: "Ana Maria da Conceição" },
    palavrasChave: ["José Vieira da Silva", "Barão da Rifaina", "genealogia"] },
  { slug: "ana-maria-da-conceicao", titulo: "Ana Maria da Conceição", href: "artigo-ana-maria-da-conceicao.html",
    resumo: "Matriarca e gestora de bens inventariados no sul de Minas Gerais, cujos recursos financeiros teriam financiado as primeiras compras de terrenos da fam…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Queluz de Minas (atual Conselheiro Lafaiete), Minas Gerais",
    anoInicio: 1770, anoFim: 1841,
    pessoa: { nome: "Ana", sobrenome: "Maria da Conceição", sexo: "F", localNascimento: "Queluz de Minas (atual Conselheiro Lafaiete), Minas Gerais", conjuge: "Capitão-Mór José Vieira da Silva" },
    palavrasChave: ["Ana Maria da Conceição", "Barão da Rifaina", "genealogia"] },
  { slug: "alferes-joaquim-antonio-de-lima", titulo: "Alferes Joaquim Antônio de Lima", href: "artigo-alferes-joaquim-antonio-de-lima.html",
    resumo: "Oficial de milícias e sesmeiro; atuou no controle do trânsito de tropas entre São Paulo e Minas Gerais, garantindo passes rurais para familiares e ali…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Minas Gerais",
    anoInicio: 1775, anoFim: 1838,
    pessoa: { nome: "Joaquim", sobrenome: "Antônio de Lima", sexo: "M", localNascimento: "Minas Gerais", conjuge: "Rita Cândida de Jesus" },
    palavrasChave: ["Joaquim Antônio de Lima", "Barão da Rifaina", "genealogia"] },
  { slug: "rita-candida-de-jesus", titulo: "Rita Cândida de Jesus", href: "artigo-rita-candida-de-jesus.html",
    resumo: "Articuladora de alianças matrimoniais endogâmicas entre famílias do sul de Minas Gerais, no contexto da formação patrimonial de terras da região.",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Minas Gerais",
    anoInicio: 1782, anoFim: 1849,
    pessoa: { nome: "Rita", sobrenome: "Cândida de Jesus", sexo: "F", localNascimento: "Minas Gerais", conjuge: "Alferes Joaquim Antônio de Lima" },
    palavrasChave: ["Rita Cândida de Jesus", "Barão da Rifaina", "genealogia"] },
  { slug: "severino-jose-vieira", titulo: "Severino José Vieira", href: "artigo-severino-jose-vieira.html",
    resumo: "Atuou na estruturação agrária e familiar na transição de Queluz de Minas para a região do Alto Paranaíba/Triângulo Mineiro.",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Queluz de Minas (atual Conselheiro Lafaiete), Minas Gerais",
    pessoa: { nome: "Severino", sobrenome: "José Vieira", sexo: "M", localNascimento: "Queluz de Minas (atual Conselheiro Lafaiete), Minas Gerais", nomePai: "José Vieira da Silva", nomeMae: "Ana Maria da Conceição", conjuge: "Maria Antônia de Lima" },
    palavrasChave: ["Severino José Vieira", "Barão da Rifaina", "genealogia"] },
  { slug: "maria-antonia-de-lima", titulo: "Maria Antônia de Lima", href: "artigo-maria-antonia-de-lima.html",
    resumo: "Matriarca familiar que participou do processo migratório e da consolidação do patrimônio da família no interior mineiro; articulou os primeiros víncul…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Minas Gerais",
    pessoa: { nome: "Maria", sobrenome: "Antônia de Lima", sexo: "F", localNascimento: "Minas Gerais", nomePai: "Joaquim Antônio de Lima", nomeMae: "Rita Cândida de Jesus", conjuge: "Severino José Vieira" },
    palavrasChave: ["Maria Antônia de Lima", "Barão da Rifaina", "genealogia"] },
  { slug: "maria-jose-da-conceicao", titulo: "Maria José da Conceição, Baronesa da Rifaina", href: "artigo-maria-jose-da-conceicao.html",
    resumo: "Baronesa da Rifaina; atuou na administração dos bens da família em Sacramento e nas redes de influência social do Triângulo Mineiro.",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Sacramento, Minas Gerais",
    pessoa: { nome: "Maria", sobrenome: "José da Conceição", sexo: "F", localNascimento: "Sacramento, Minas Gerais", nomePai: "Manuel Joaquim de Sant'Ana", nomeMae: "Maria José da Silva", conjuge: "Vicente de Paula Vieira" },
    palavrasChave: ["Maria José da Conceição", "Barão da Rifaina", "genealogia"] },
  { slug: "manuel-joaquim-de-santana", titulo: "Manuel Joaquim de Sant'Ana", href: "artigo-manuel-joaquim-de-santana.html",
    resumo: "Atuou na posse e exploração de terras na divisa entre Minas Gerais e São Paulo.",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Divisa entre Minas Gerais e São Paulo",
    pessoa: { nome: "Manuel", sobrenome: "Joaquim de Sant'Ana", sexo: "M", localNascimento: "Divisa entre Minas Gerais e São Paulo", conjuge: "Maria José da Silva" },
    palavrasChave: ["Manuel Joaquim de Sant'Ana", "Barão da Rifaina", "genealogia"] },
  { slug: "maria-jose-da-silva-sogra-do-barao", titulo: "Maria José da Silva (sogra do Barão da Rifaina)", href: "artigo-maria-jose-da-silva-sogra-do-barao.html",
    resumo: "Integrante das famílias latifundiárias tradicionais ligadas ao povoamento local da divisa entre Minas Gerais e São Paulo, na região de Franca e Pedreg…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Franca, São Paulo",
    pessoa: { nome: "Maria", sobrenome: "José da Silva", sexo: "F", localNascimento: "Franca, São Paulo", conjuge: "Manuel Joaquim de Sant'Ana" },
    palavrasChave: ["Maria José da Silva", "Barão da Rifaina", "genealogia"] },
  { slug: "ernesto-de-paula-vieira", titulo: "Ernesto de Paula Vieira", href: "artigo-ernesto-de-paula-vieira.html",
    resumo: "Atuou na continuidade do patrimônio agrícola e nos negócios da família no município de Sacramento e arredores, e na gestão do espólio agrícola e moder…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Sacramento, Minas Gerais",
    pessoa: { nome: "Ernesto", sobrenome: "de Paula Vieira", sexo: "M", localNascimento: "Sacramento, Minas Gerais", nomePai: "Vicente de Paula Vieira", nomeMae: "Maria José da Conceição", conjuge: "Amélia Vieira" },
    palavrasChave: ["Ernesto de Paula Vieira", "Barão da Rifaina", "genealogia"] },
  { slug: "amelia-vieira", titulo: "Amélia Vieira", href: "artigo-amelia-vieira.html",
    resumo: "Atuou na gestão doméstica e manutenção do núcleo familiar dos Vieira, mantendo as alianças locais da família no início do período republicano.",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Sacramento, Minas Gerais",
    pessoa: { nome: "Amélia", sobrenome: "Vieira", sexo: "F", localNascimento: "Sacramento, Minas Gerais", conjuge: "Ernesto de Paula Vieira" },
    palavrasChave: ["Amélia Vieira", "Barão da Rifaina", "genealogia"] },
  { slug: "agnelo-de-paula-vieira", titulo: "Agnelo de Paula Vieira", href: "artigo-agnelo-de-paula-vieira.html",
    resumo: "Representou a transição da família para atividades urbanas e comerciais no século XX, atuando no setor comercial e imobiliário em Sacramento e Uberaba…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Sacramento, Minas Gerais",
    pessoa: { nome: "Agnelo", sobrenome: "de Paula Vieira", sexo: "M", localNascimento: "Sacramento, Minas Gerais", nomePai: "Ernesto de Paula Vieira", nomeMae: "Amélia Vieira", conjuge: "Maria Cândida Vieira" },
    palavrasChave: ["Agnelo de Paula Vieira", "Barão da Rifaina", "genealogia"] },
  { slug: "maria-candida-vieira", titulo: "Maria Cândida Vieira", href: "artigo-maria-candida-vieira.html",
    resumo: "Preservou a memória histórica da família no interior mineiro e zelou pela conservação dos documentos e do acervo pessoal ligado ao título imperial do …",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Sacramento, Minas Gerais",
    pessoa: { nome: "Maria", sobrenome: "Cândida Vieira", sexo: "F", localNascimento: "Sacramento, Minas Gerais", conjuge: "Agnelo de Paula Vieira" },
    palavrasChave: ["Maria Cândida Vieira", "Barão da Rifaina", "genealogia"] },
  { slug: "descendente-doadora-do-acervo-barao-da-rifaina", titulo: "Descendente doadora do acervo do Barão da Rifaina", href: "artigo-descendente-doadora-do-acervo-barao-da-rifaina.html",
    resumo: "Atuou na preservação da memória histórica regional ao destinar documentos oficiais, correspondências e registros da atuação política e pessoal do Barã…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Sacramento, Minas Gerais",
    pessoa: { sexo: "F", localNascimento: "Sacramento, Minas Gerais" },
    palavrasChave: ["Descendente doadora do acervo do Barão da Rifaina", "Barão da Rifaina", "genealogia"] },
  { slug: "vicentina-de-paula-vieira", titulo: "Vicentina de Paula Vieira", href: "artigo-vicentina-de-paula-vieira.html",
    resumo: "Descendente registrada histórica e genealogicamente no interior de Minas Gerais no século XX.",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Minas Gerais",
    pessoa: { nome: "Vicentina", sobrenome: "de Paula Vieira", sexo: "F", localNascimento: "Minas Gerais" },
    palavrasChave: ["Vicentina de Paula Vieira", "Barão da Rifaina", "genealogia"] },
  { slug: "capitao-vicente-de-paula-vieira-junior", titulo: "Capitão Vicente de Paula Vieira Júnior", href: "artigo-capitao-vicente-de-paula-vieira-junior.html",
    resumo: "Político republicano inicial, vereador em Sacramento e fazendeiro; atuou na transição do trabalho escravizado para o trabalho assalariado e colono ita…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Sacramento, Minas Gerais",
    anoInicio: 1860, anoFim: 1928,
    pessoa: { nome: "Vicente", sobrenome: "de Paula Vieira Júnior", sexo: "M", localNascimento: "Sacramento, Minas Gerais", nomePai: "Vicente de Paula Vieira", nomeMae: "Maria José da Conceição" },
    palavrasChave: ["Vicente de Paula Vieira Júnior", "Barão da Rifaina", "genealogia"] },
  { slug: "maria-jose-vieira-de-almeida", titulo: "Maria José Vieira de Almeida", href: "artigo-maria-jose-vieira-de-almeida.html",
    resumo: "Integrou a elite filantrópica regional; casou-se com a tradicional família Almeida, unindo forças políticas de Uberaba e Sacramento; ligou a família a…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Uberaba, Minas Gerais",
    anoInicio: 1863, anoFim: 1935,
    pessoa: { nome: "Maria", sobrenome: "José Vieira de Almeida", sexo: "F", localNascimento: "Uberaba, Minas Gerais", nomePai: "Vicente de Paula Vieira", nomeMae: "Maria José da Conceição" },
    palavrasChave: ["Maria José Vieira de Almeida", "Barão da Rifaina", "genealogia"] },
  { slug: "jose-vieira-de-paula", titulo: "Doutor José Vieira de Paula", href: "artigo-jose-vieira-de-paula.html",
    resumo: "Bacharel em Direito pela Faculdade de Direito de São Paulo (Largo de São Francisco); atuou como juiz municipal, advogado e articulista defensor da ins…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "São Paulo, São Paulo",
    anoInicio: 1867, anoFim: 1941,
    pessoa: { nome: "José", sobrenome: "Vieira de Paula", sexo: "M", localNascimento: "São Paulo, São Paulo", nomePai: "Vicente de Paula Vieira", nomeMae: "Maria José da Conceição" },
    palavrasChave: ["José Vieira de Paula", "Barão da Rifaina", "genealogia"] },
  { slug: "olympia-vieira-de-santana", titulo: "Olympia Vieira de Santana", href: "artigo-olympia-vieira-de-santana.html",
    resumo: "Matriarca e gestora de patrimônio urbano e rural em Rifaina e Franca; manteve acervos documentais e correspondências do período imperial; manteve o es…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Rifaina, São Paulo",
    anoInicio: 1872, anoFim: 1948,
    pessoa: { nome: "Olympia", sobrenome: "Vieira de Santana", sexo: "F", localNascimento: "Rifaina, São Paulo", nomePai: "Vicente de Paula Vieira", nomeMae: "Maria José da Conceição" },
    palavrasChave: ["Olympia Vieira de Santana", "Barão da Rifaina", "genealogia"] },
  { slug: "vicente-de-paula-vieira-neto", titulo: "Coronel Vicente de Paula Vieira Neto (\"Vicentinho\")", href: "artigo-vicente-de-paula-vieira-neto.html",
    resumo: "Chefe político da República Velha em Sacramento; prefeito municipal e influente cafeicultor no ciclo de expansão da Estrada de Ferro Mogiana.",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Sacramento, Minas Gerais",
    anoInicio: 1888, anoFim: 1962,
    pessoa: { nome: "Vicente", sobrenome: "de Paula Vieira Neto", sexo: "M", localNascimento: "Sacramento, Minas Gerais" },
    palavrasChave: ["Vicente de Paula Vieira Neto", "Barão da Rifaina", "genealogia"] },
  { slug: "laura-vieira-de-oliveira", titulo: "Laura Vieira de Oliveira", href: "artigo-laura-vieira-de-oliveira.html",
    resumo: "Educadora e fundadora de programas assistenciais no Triângulo Mineiro; promoveu a preservação da memória histórica da navegação do Rio Grande.",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Sacramento, Minas Gerais",
    anoInicio: 1892, anoFim: 1970,
    pessoa: { nome: "Laura", sobrenome: "Vieira de Oliveira", sexo: "F", localNascimento: "Sacramento, Minas Gerais" },
    palavrasChave: ["Laura Vieira de Oliveira", "Barão da Rifaina", "genealogia"] },
  { slug: "tenente-joaquim-jose-vieira", titulo: "Tenente Joaquim José Vieira", href: "artigo-tenente-joaquim-jose-vieira.html",
    resumo: "Oficial da Guarda Nacional e subdelegado em Sacramento; atuou no policiamento rural, na contenção de conflitos fundiários e na segurança do transporte…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Sacramento, Minas Gerais",
    anoInicio: 1828, anoFim: 1891,
    pessoa: { nome: "Joaquim", sobrenome: "José Vieira", sexo: "M", localNascimento: "Sacramento, Minas Gerais", nomePai: "Severino José Vieira", nomeMae: "Maria Antônia de Lima" },
    palavrasChave: ["Joaquim José Vieira", "Barão da Rifaina", "genealogia"] },
  { slug: "ana-antonia-de-lima", titulo: "Ana Antônia de Lima (\"Ana Vieira\")", href: "artigo-ana-antonia-de-lima.html",
    resumo: "Proprietária fundiária e benemérita; manteve doações para a construção da Matriz de Sacramento e custeou a alforria paroquial de crianças ingênuas.",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Sacramento, Minas Gerais",
    anoInicio: 1830, anoFim: 1898,
    pessoa: { nome: "Ana", sobrenome: "Antônia de Lima", sexo: "F", localNascimento: "Sacramento, Minas Gerais", nomePai: "Severino José Vieira", nomeMae: "Maria Antônia de Lima" },
    palavrasChave: ["Ana Antônia de Lima", "Barão da Rifaina", "genealogia"] },
  { slug: "major-severino-jose-vieira-filho", titulo: "Major Severino José Vieira Filho", href: "artigo-major-severino-jose-vieira-filho.html",
    resumo: "Liderança do Partido Liberal em Uberaba e conselheiro municipal; defendeu melhorias viárias para a ligação entre Rifaina, Pedregulho e Uberaba.",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Uberaba, Minas Gerais",
    anoInicio: 1836, anoFim: 1904,
    pessoa: { nome: "Severino", sobrenome: "José Vieira Filho", sexo: "M", localNascimento: "Uberaba, Minas Gerais", nomePai: "Severino José Vieira", nomeMae: "Maria Antônia de Lima" },
    palavrasChave: ["Severino José Vieira Filho", "Barão da Rifaina", "genealogia"] },
  { slug: "capitao-manuel-antonio-de-santana", titulo: "Capitão Manuel Antônio de Santana", href: "artigo-capitao-manuel-antonio-de-santana.html",
    resumo: "Produtor rural e negociante de gado na fronteira paulista-mineira; atuou como eleitor de paróquia em Rifaina para a sustentação das bancadas liberais;…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Rifaina, São Paulo",
    anoInicio: 1825, anoFim: 1889,
    pessoa: { nome: "Manuel", sobrenome: "Antônio de Santana", sexo: "M", localNascimento: "Rifaina, São Paulo", nomePai: "Manuel Joaquim de Sant'Ana", nomeMae: "Maria José da Silva" },
    palavrasChave: ["Manuel Antônio de Santana", "Barão da Rifaina", "genealogia"] },
  { slug: "francisca-de-paula-santana", titulo: "Francisca de Paula Santana", href: "artigo-francisca-de-paula-santana.html",
    resumo: "Administradora de fazendas de café na região de Rifaina/Pedregulho; manteve estreita rede de solidariedade com ordens terceiras locais.",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Rifaina, São Paulo",
    anoInicio: 1831, anoFim: 1901,
    pessoa: { nome: "Francisca", sobrenome: "de Paula Santana", sexo: "F", localNascimento: "Rifaina, São Paulo", nomePai: "Manuel Joaquim de Sant'Ana", nomeMae: "Maria José da Silva" },
    palavrasChave: ["Francisca de Paula Santana", "Barão da Rifaina", "genealogia"] },
  { slug: "coronel-jose-affonso-de-almeida", titulo: "Coronel José Affonso de Almeida", href: "artigo-coronel-jose-affonso-de-almeida.html",
    resumo: "Liderança política e militar do Triângulo Mineiro, articulada com os grupos dos Borges e dos Vieira nas articulações legislativas e locais em prol do …",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Uberaba, Minas Gerais",
    pessoa: { nome: "José", sobrenome: "Affonso de Almeida", sexo: "M", localNascimento: "Uberaba, Minas Gerais" },
    palavrasChave: ["José Affonso de Almeida", "Barão da Rifaina", "genealogia"] },
  { slug: "coronel-antonio-carlos-da-silva", titulo: "Coronel Antônio Carlos da Silva", href: "artigo-coronel-antonio-carlos-da-silva.html",
    resumo: "Chefe político da região do Desemboque/Sacramento; comandante da Guarda Nacional, atuou lado a lado com o Barão na arregimentação de votos liberais na…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Sacramento, Minas Gerais",
    anoInicio: 1842, anoFim: 1915,
    pessoa: { nome: "Antônio", sobrenome: "Carlos da Silva", sexo: "M", localNascimento: "Sacramento, Minas Gerais" },
    palavrasChave: ["Antônio Carlos da Silva", "Barão da Rifaina", "genealogia"] },
  { slug: "major-joao-baptista-de-siqueira", titulo: "Major João Baptista de Siqueira", href: "artigo-major-joao-baptista-de-siqueira.html",
    resumo: "Responsável pelo recrutamento militar local e pela manutenção das vias rurais na região de Sacramento, Desemboque e Rifaina, junto à Guarda Nacional.",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Sacramento, Minas Gerais",
    pessoa: { nome: "João", sobrenome: "Baptista de Siqueira", sexo: "M", localNascimento: "Sacramento, Minas Gerais" },
    palavrasChave: ["João Baptista de Siqueira", "Barão da Rifaina", "genealogia"] },
  { slug: "capitao-francisco-jose-de-oliveira", titulo: "Capitão Francisco José de Oliveira", href: "artigo-capitao-francisco-jose-de-oliveira.html",
    resumo: "Intendente de suprimentos militares para o contingente local da Guarda Nacional na região de Sacramento, Desemboque e Rifaina.",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Sacramento, Minas Gerais",
    pessoa: { nome: "Francisco", sobrenome: "José de Oliveira", sexo: "M", localNascimento: "Sacramento, Minas Gerais" },
    palavrasChave: ["Francisco José de Oliveira", "Barão da Rifaina", "genealogia"] },
  { slug: "padre-hermogenes-cassimiro-de-araujo-brunswick", titulo: "Padre Hermógenes Cassimiro de Araujo Brunswick", href: "artigo-padre-hermogenes-cassimiro-de-araujo-brunswick.html",
    resumo: "Primeiro deputado eleito pelo Triângulo Mineiro; abriu caminho parlamentar e institucional para líderes posteriores, como o Barão da Rifaina. [citação…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Triângulo Mineiro, Minas Gerais",
    anoInicio: 1780, anoFim: 1861,
    pessoa: { nome: "Hermógenes", sobrenome: "Cassimiro de Araujo Brunswick", sexo: "M", localNascimento: "Triângulo Mineiro, Minas Gerais" },
    palavrasChave: ["Hermógenes Cassimiro de Araujo Brunswick", "Barão da Rifaina", "genealogia"] },
  { slug: "doutor-antonio-de-cerqueira-lima", titulo: "Juiz de Direito Doutor Antônio de Cerqueira Lima", href: "artigo-doutor-antonio-de-cerqueira-lima.html",
    resumo: "Magistrado da Comarca do Triângulo; presidiu inventários da família Vieira e atuou na mediação legal de terras e na homologação de cartas de alforria …",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Triângulo Mineiro, Minas Gerais",
    anoInicio: 1835, anoFim: 1902,
    pessoa: { nome: "Antônio", sobrenome: "de Cerqueira Lima", sexo: "M", localNascimento: "Triângulo Mineiro, Minas Gerais" },
    palavrasChave: ["Antônio de Cerqueira Lima", "Barão da Rifaina", "genealogia"] },
  { slug: "doutor-fidelis-reis", titulo: "Doutor Fidelis Reis", href: "artigo-doutor-fidelis-reis.html",
    resumo: "Deputado federal e intelectual; articulou pautas de desenvolvimento agrícola e educacional herdeiras das propostas do Barão da Rifaina. [citação neces…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Uberaba, Minas Gerais",
    anoInicio: 1888, anoFim: 1962,
    pessoa: { nome: "Fidelis", sobrenome: "Reis", sexo: "M", localNascimento: "Uberaba, Minas Gerais" },
    palavrasChave: ["Fidelis Reis", "Barão da Rifaina", "genealogia"] },
  { slug: "senador-manuel-da-silva-prata", titulo: "Senador Manuel da Silva Prata", href: "artigo-senador-manuel-da-silva-prata.html",
    resumo: "Defendeu no Senado Provincial de Minas Gerais a emancipação judiciária e a criação de novas comarcas para Uberaba, Sacramento e Araxá.",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Minas Gerais",
    anoInicio: 1840, anoFim: 1912,
    pessoa: { nome: "Manuel", sobrenome: "da Silva Prata", sexo: "M", localNascimento: "Minas Gerais" },
    palavrasChave: ["Manuel da Silva Prata", "Barão da Rifaina", "genealogia"] },
  { slug: "afonso-pena", titulo: "Afonso Pena", href: "artigo-afonso-pena.html",
    resumo: "Afonso Augusto Moreira Pena foi um político mineiro, presidente da província de Minas Gerais e, de 1906 até sua morte em 1909, presidente da República…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Santa Bárbara, Minas Gerais",
    anoInicio: 1847, anoFim: 1909,
    pessoa: { nome: "Afonso", sobrenome: "Pena", sexo: "M", localNascimento: "Santa Bárbara, Minas Gerais" },
    palavrasChave: ["Afonso Pena", "Barão da Rifaina", "genealogia"] },
  { slug: "lafayette-rodrigues-pereira", titulo: "Lafayette Rodrigues Pereira", href: "artigo-lafayette-rodrigues-pereira.html",
    resumo: "Jurista, professor e político mineiro; foi presidente do Conselho de Ministros do Império do Brasil (1883–1884) e senador. [citação necessária] para a…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Barbacena, Minas Gerais",
    anoInicio: 1834, anoFim: 1917,
    pessoa: { nome: "Lafayette", sobrenome: "Rodrigues Pereira", sexo: "M", localNascimento: "Barbacena, Minas Gerais" },
    palavrasChave: ["Lafayette Rodrigues Pereira", "Barão da Rifaina", "genealogia"] },
  { slug: "martim-francisco-ribeiro-de-andrada", titulo: "Martim Francisco Ribeiro de Andrada", href: "artigo-martim-francisco-ribeiro-de-andrada.html",
    resumo: "Deputado citado como aliado partidário nas pautas da agricultura nacional. Há mais de uma figura histórica com este nome na tradicional família Andrad…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Minas Gerais",
    pessoa: { nome: "Martim", sobrenome: "Francisco Ribeiro de Andrada", sexo: "M", localNascimento: "Minas Gerais" },
    palavrasChave: ["Martim Francisco Ribeiro de Andrada", "Barão da Rifaina", "genealogia"] },
  { slug: "joaquim-delaney", titulo: "Joaquim Delaney", href: "artigo-joaquim-delaney.html",
    resumo: "Deputado provincial; segundo a fonte usada nesta seção, votou favoravelmente a verbas para estradas no Alto Paranaíba. [citação necessária] para maior…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Minas Gerais",
    pessoa: { nome: "Joaquim", sobrenome: "Delaney", sexo: "M", localNascimento: "Minas Gerais" },
    palavrasChave: ["Joaquim Delaney", "Barão da Rifaina", "genealogia"] },
  { slug: "antonio-augusto-de-lima", titulo: "Antônio Augusto de Lima", href: "artigo-antonio-augusto-de-lima.html",
    resumo: "Intelectual e deputado liberal citado como tendo articulado propostas de instrução pública com o Barão. Existe um poeta parnasiano mineiro de nome sem…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Minas Gerais",
    pessoa: { nome: "Antônio", sobrenome: "Augusto de Lima", sexo: "M", localNascimento: "Minas Gerais" },
    palavrasChave: ["Antônio Augusto de Lima", "Barão da Rifaina", "genealogia"] },
  { slug: "francisco-luis-da-veiga", titulo: "Francisco Luís da Veiga", href: "artigo-francisco-luis-da-veiga.html",
    resumo: "Jornalista e político; segundo a fonte usada nesta seção, teria utilizado a imprensa de Ouro Preto para divulgar discursos do Barão. [citação necessár…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Ouro Preto, Minas Gerais",
    pessoa: { nome: "Francisco", sobrenome: "Luís da Veiga", sexo: "M", localNascimento: "Ouro Preto, Minas Gerais" },
    palavrasChave: ["Francisco Luís da Veiga", "Barão da Rifaina", "genealogia"] },
  { slug: "bernardo-avelino-gaviao-peixoto", titulo: "Bernardo Avelino Gavião Peixoto", href: "artigo-bernardo-avelino-gaviao-peixoto.html",
    resumo: "Político aliado citado como tendo atuado no limite entre Minas Gerais e São Paulo, intermediando o trânsito de mercadorias. Há um político paulista hi…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Divisa entre Minas Gerais e São Paulo",
    pessoa: { nome: "Bernardo", sobrenome: "Avelino Gavião Peixoto", sexo: "M", localNascimento: "Divisa entre Minas Gerais e São Paulo" },
    palavrasChave: ["Bernardo Avelino Gavião Peixoto", "Barão da Rifaina", "genealogia"] },
  { slug: "jose-bento-leite-ferreira-de-melo", titulo: "José Bento Leite Ferreira de Melo", href: "artigo-jose-bento-leite-ferreira-de-melo.html",
    resumo: "Citado como influência que teria moldado a formação do Partido Liberal no sul e oeste de Minas Gerais. [citação necessária] para maiores detalhes biog…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Minas Gerais",
    pessoa: { nome: "José", sobrenome: "Bento Leite Ferreira de Melo", sexo: "M", localNascimento: "Minas Gerais" },
    palavrasChave: ["José Bento Leite Ferreira de Melo", "Barão da Rifaina", "genealogia"] },
  { slug: "teofilo-otoni", titulo: "Teófilo Otoni", href: "artigo-teofilo-otoni.html",
    resumo: "Cristiano Benedito Otoni, conhecido como Teófilo Otoni, foi um político, empresário e colonizador mineiro, fundador da Companhia de Comércio e Navegaç…",
    categorias: ["Pessoas", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Serro, Minas Gerais",
    anoInicio: 1807, anoFim: 1869,
    pessoa: { nome: "Teófilo", sobrenome: "Otoni", sexo: "M", localNascimento: "Serro, Minas Gerais" },
    palavrasChave: ["Teófilo Otoni", "Barão da Rifaina", "genealogia"] },
  { slug: "guarda-nacional-no-triangulo-mineiro", titulo: "Guarda Nacional no Triângulo Mineiro e Alto Paranaíba", href: "artigo-guarda-nacional-no-triangulo-mineiro.html",
    resumo: "Milícia cidadã criada em 1831, recrutada entre proprietários locais; forneceu postos de Tenente e Alferes a fazendeiros do Triângulo Mineiro e Alto Paranaíba, incluindo aliados do Barão da Rifaina.",
    categorias: ["Instituições", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Sacramento, Minas Gerais",
    anoInicio: 1831, anoFim: null,
    palavrasChave: ["Guarda Nacional no Triângulo Mineiro e Alto Paranaíba", "Barão da Rifaina"] },
  { slug: "eleitorado-paroquial-partido-liberal-triangulo-mineiro", titulo: "Eleitorado paroquial e Partido Liberal em Sacramento, Uberaba e Araxá", href: "artigo-eleitorado-paroquial-partido-liberal-triangulo-mineiro.html",
    resumo: "O sistema eleitoral censitário e indireto do Segundo Reinado, com eleitores de paróquia e a atuação do Partido Liberal nas paróquias de Sacramento, Uberaba e Araxá.",
    categorias: ["Instituições", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Uberaba, Minas Gerais",
    palavrasChave: ["Eleitorado paroquial e Partido Liberal em Sacramento, Uberaba e Araxá", "Barão da Rifaina"] },
  { slug: "justica-de-paz-administracao-municipal-sacramento-rifaina", titulo: "Justiça de paz e administração municipal de Sacramento e Rifaina", href: "artigo-justica-de-paz-administracao-municipal-sacramento-rifaina.html",
    resumo: "O cargo eletivo de Juiz de Paz, criado em 1827, e sua importância na administração municipal e na vida política de Sacramento e do distrito de Rifaina ao longo do século XIX.",
    categorias: ["Instituições", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Sacramento, Minas Gerais",
    anoInicio: 1827, anoFim: null,
    palavrasChave: ["Justiça de paz e administração municipal de Sacramento e Rifaina", "Barão da Rifaina"] },
  { slug: "estrada-de-ferro-mogiana", titulo: "Estrada de Ferro Mogiana", href: "artigo-estrada-de-ferro-mogiana.html",
    resumo: "A Companhia Mogiana de Estradas de Ferro, fundada em 1872 em Campinas (SP), estendeu ramais ao Triângulo Mineiro a partir do final do século XIX, impulsionando o comércio regional de café e gado.",
    categorias: ["Infraestrutura e economia", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Uberaba, Minas Gerais",
    anoInicio: 1872, anoFim: 1971,
    palavrasChave: ["Estrada de Ferro Mogiana", "Barão da Rifaina"] },
  { slug: "rio-grande", titulo: "Rio Grande", href: "artigo-rio-grande.html",
    resumo: "Um dos principais rios que delimitam o Triângulo Mineiro, afluente do rio Paraná, citado no levantamento genealógico do Barão da Rifaina como referência geográfica das propriedades da família.",
    categorias: ["Geografia", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Rio Grande, Minas Gerais",
    palavrasChave: ["Rio Grande", "Barão da Rifaina"] },
  { slug: "ciclo-do-cafe-no-triangulo-mineiro", titulo: "Ciclo do café no Triângulo Mineiro e Alto Paranaíba", href: "artigo-ciclo-do-cafe-no-triangulo-mineiro.html",
    resumo: "A expansão tardia da cafeicultura para o Triângulo Mineiro e o Alto Paranaíba no final do século XIX, e seu papel na formação de uma elite de fazendeiros e criadores de gado da região.",
    categorias: ["Infraestrutura e economia", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Araxá, Minas Gerais",
    palavrasChave: ["Ciclo do café no Triângulo Mineiro e Alto Paranaíba", "Barão da Rifaina"] },
  { slug: "paroquia-nossa-senhora-do-patrocinio-santissimo-sacramento", titulo: "Paróquia de Nossa Senhora do Patrocínio do Santíssimo Sacramento", href: "artigo-paroquia-nossa-senhora-do-patrocinio-santissimo-sacramento.html",
    resumo: "A paróquia que deu origem ao município de Sacramento, Minas Gerais, e serviu de referência administrativa e religiosa para o registro de nascimentos, casamentos e óbitos da família do Barão da Rifaina.",
    categorias: ["Instituições", "Genealogia Barão da Rifaina"], tipo: "artigo",
    local: "Sacramento, Minas Gerais",
    palavrasChave: ["Paróquia de Nossa Senhora do Patrocínio do Santíssimo Sacramento", "Barão da Rifaina"] },
  { slug: "domingos-da-silva-e-oliveira", titulo: "Capitão Domingos da Silva e Oliveira", href: "artigo-domingos-da-silva-e-oliveira.html",
    resumo: "Cofundador do povoado que deu origem a Uberaba, ao lado do irmão, o Sargento-Mor/Major Eustáquio da Silva e Oliveira. Foi juiz municipal, delegado de …",
    categorias: ["Pessoas", "História de Minas Gerais"], tipo: "artigo",
    local: "Uberaba, Minas Gerais",
    anoInicio: 1782, anoFim: 1852,
    pessoa: { nome: "Domingos", sobrenome: "da Silva e Oliveira", localNascimento: "Uberaba, Minas Gerais" },
    palavrasChave: ["Domingos da Silva e Oliveira", "Triângulo Mineiro", "história"] },
  { slug: "eustaquio-da-silva-e-oliveira", titulo: "Major Eustáquio da Silva e Oliveira", href: "artigo-eustaquio-da-silva-e-oliveira.html",
    resumo: "Cofundador, ao lado do irmão Capitão Domingos da Silva e Oliveira, do povoado que deu origem ao município de Uberaba, no início do século XIX.",
    categorias: ["Pessoas", "História de Minas Gerais"], tipo: "artigo",
    local: "Uberaba, Minas Gerais",
    pessoa: { nome: "Eustáquio", sobrenome: "da Silva e Oliveira", localNascimento: "Uberaba, Minas Gerais" },
    palavrasChave: ["Eustáquio da Silva e Oliveira", "Triângulo Mineiro", "história"] },
  { slug: "frei-eugenio-maria-da-genova", titulo: "Frei Eugênio Maria da Gênova", href: "artigo-frei-eugenio-maria-da-genova.html",
    resumo: "Nascido João Batista Maberino, tornou-se frade capuchinho e atuou em Uberaba no Segundo Reinado, onde fundou o Cemitério São Miguel e teve papel relev…",
    categorias: ["Pessoas", "História de Minas Gerais"], tipo: "artigo",
    local: "Uberaba, Minas Gerais",
    anoInicio: 1812, anoFim: 1871,
    pessoa: { nome: "Frei", sobrenome: "Eugênio Maria da Gênova", localNascimento: "Uberaba, Minas Gerais" },
    palavrasChave: ["Frei Eugênio Maria da Gênova", "Triângulo Mineiro", "história"] },
  { slug: "padre-zeferino-batista-do-carmo", titulo: "Padre Zeferino Batista do Carmo", href: "artigo-padre-zeferino-batista-do-carmo.html",
    resumo: "Atuou como pároco em Uberaba durante o Império, onde é lembrado por introduzir a horticultura e a vinicultura na região, construir a Igreja do Rosário…",
    categorias: ["Pessoas", "História de Minas Gerais"], tipo: "artigo",
    local: "Uberaba, Minas Gerais",
    anoInicio: 1791, anoFim: 1873,
    pessoa: { nome: "Zeferino", sobrenome: "Batista do Carmo", localNascimento: "Uberaba, Minas Gerais" },
    palavrasChave: ["Zeferino Batista do Carmo", "Triângulo Mineiro", "história"] },
  { slug: "fidelis-goncalves-reis", titulo: "Fidélis Gonçalves Reis", href: "artigo-fidelis-goncalves-reis.html",
    resumo: "Deputado federal por Minas Gerais, ficou conhecido por ser o autor da chamada \"Lei Fidélis Reis\", de 1927, sobre ensino profissional agrícola no Brasi…",
    categorias: ["Pessoas", "História de Minas Gerais"], tipo: "artigo",
    local: "Uberaba, Minas Gerais",
    anoInicio: 1880, anoFim: 1962,
    pessoa: { nome: "Fidélis", sobrenome: "Gonçalves Reis", localNascimento: "Uberaba, Minas Gerais" },
    palavrasChave: ["Fidélis Gonçalves Reis", "Triângulo Mineiro", "história"] },
  { slug: "crispim-jacques-bias-fortes", titulo: "Chrispim Jacques Bias Fortes", href: "artigo-crispim-jacques-bias-fortes.html",
    resumo: "Advogado e deputado provincial, chegou a presidente (equivalente a governador) do estado de Minas Gerais entre 1894 e 1898. Sua carreira política docu…",
    categorias: ["Pessoas", "História de Minas Gerais"], tipo: "artigo",
    local: "Barbacena, Minas Gerais",
    anoInicio: 1847, anoFim: 1917,
    pessoa: { nome: "Chrispim", sobrenome: "Jacques Bias Fortes", localNascimento: "Barbacena, Minas Gerais" },
    palavrasChave: ["Chrispim Jacques Bias Fortes", "Triângulo Mineiro", "história"] },
  { slug: "elite-agraria-escravocrata-do-triangulo-mineiro-imperial", titulo: "Elite agrária escravocrata do Triângulo Mineiro no Império", href: "artigo-elite-agraria-escravocrata-do-triangulo-mineiro-imperial.html",
    resumo: "Os fazendeiros, criadores de gado e comerciantes que sustentaram a economia escravista do Triângulo Mineiro e do Alto Paranaíba durante o Império (1822–1889).",
    categorias: ["História de Minas Gerais", "Instituições"], tipo: "artigo",
    local: "Uberaba, Minas Gerais",
    anoInicio: 1822, anoFim: 1889,
    palavrasChave: ["Elite agrária escravocrata do Triângulo Mineiro no Império", "Barão da Rifaina"] },
  { slug: "clero-catolico-no-triangulo-mineiro-imperial", titulo: "Clero católico no Triângulo Mineiro durante o Império", href: "artigo-clero-catolico-no-triangulo-mineiro-imperial.html",
    resumo: "Vigários, capelães e frades que atuaram nas paróquias do Triângulo Mineiro durante o Segundo Reinado, registrando batismos, casamentos e óbitos e mediando a vida social da região.",
    categorias: ["História de Minas Gerais", "Instituições"], tipo: "artigo",
    local: "Uberaba, Minas Gerais",
    anoInicio: 1822, anoFim: 1889,
    palavrasChave: ["Clero católico no Triângulo Mineiro durante o Império", "Barão da Rifaina"] },
  { slug: "escravidao-e-alforria-no-triangulo-mineiro-imperial", titulo: "Escravidão e alforria no Triângulo Mineiro durante o Império", href: "artigo-escravidao-e-alforria-no-triangulo-mineiro-imperial.html",
    resumo: "O trabalho escravizado, os processos de alforria e a resistência de pessoas escravizadas no Triângulo Mineiro ao longo do Império, incluindo a transição para o trabalho livre entre a Lei do Ventre Livre (1871) e a Lei Áurea (1888).",
    categorias: ["História de Minas Gerais", "Instituições"], tipo: "artigo",
    local: "Uberaba, Minas Gerais",
    anoInicio: 1822, anoFim: 1888,
    palavrasChave: ["Escravidão e alforria no Triângulo Mineiro durante o Império", "Barão da Rifaina"] },
  { slug: "violencia-domestica-contra-pessoas-escravizadas-no-brasil-imperial", titulo: "Violência doméstica contra pessoas escravizadas no Brasil Imperial", href: "artigo-violencia-domestica-contra-pessoas-escravizadas-no-brasil-imperial.html",
    resumo: "O que a historiografia acadêmica documenta sobre castigos físicos e violência cometida no ambiente doméstico contra mulheres, homens e crianças escravizados durante o Império brasileiro (1822–1889), incluindo o Triângulo Mineiro.",
    categorias: ["História de Minas Gerais", "Instituições"], tipo: "artigo",
    local: "Triângulo Mineiro, Minas Gerais",
    anoInicio: 1822, anoFim: 1889,
    palavrasChave: ["Violência doméstica contra pessoas escravizadas no Brasil Imperial", "Barão da Rifaina"] },
  { slug: "minas-gerais", titulo: "Minas Gerais", href: "artigo-minas-gerais.html",
    resumo: "Estado da região Sudeste do Brasil, o segundo mais populoso e o segundo maior em área do país, onde se localiza o Triângulo Mineiro.",
    categorias: ["Geografia"], tipo: "artigo",
    local: "Minas Gerais, Brasil",
    palavrasChave: ["Belo Horizonte", "Inconfidência Mineira", "Quadrilátero Ferrífero"] },
  { slug: "goias", titulo: "Goiás", href: "artigo-goias.html",
    resumo: "Estado da região Centro-Oeste do Brasil, que faz fronteira com o Triângulo Mineiro a oeste.",
    categorias: ["Geografia"], tipo: "artigo",
    local: "Goiás, Brasil",
    palavrasChave: ["Goiânia", "Centro-Oeste"] },
  { slug: "sao-paulo", titulo: "São Paulo (estado)", href: "artigo-sao-paulo.html",
    resumo: "Estado da região Sudeste do Brasil, o mais populoso do país, que faz fronteira com o Triângulo Mineiro pelo rio Grande.",
    categorias: ["Geografia"], tipo: "artigo",
    local: "São Paulo, Brasil",
    palavrasChave: ["estado de São Paulo", "rio Grande"] },
  { slug: "parana", titulo: "Rio Paraná", href: "artigo-parana.html",
    resumo: "Um dos maiores rios da América do Sul, formado pela confluência dos rios Grande e Paranaíba.",
    categorias: ["Geografia"], tipo: "artigo",
    local: "Rio Paraná, Brasil",
    palavrasChave: ["Itaipu", "bacia do Paraná", "hidrografia"] },
  { slug: "instituto-barao-da-rifaina", titulo: "Instituto Barão da Rifaina", href: "artigo-instituto-barao-da-rifaina.html",
    resumo: "Organização dedicada à preservação cultural e histórica de Sacramento (MG) e do Triângulo Mineiro, mantenedora da TriânguloLeaks.",
    categorias: ["Instituições"], tipo: "artigo",
    local: "Sacramento, Triângulo Mineiro, Minas Gerais",
    palavrasChave: ["TriânguloLeaks", "Barão da Rifaina", "Sacramento"] },
];

/* ----------------------------------------------------------------
   2. Autoindexação: funde, em tempo de carregamento, o índice estático
   acima com o índice local (localStorage "tp:indice-local",
   alimentado por TP.indexarArtigo em js/estado.js sempre que um
   artigo é criado ou editado). Feito aqui — sem depender de
   window.TP — porque em algumas páginas js/indice.js é carregado
   ANTES de js/estado.js; assim window.TP_INDICE já sai desta tag
   <script> com tudo mesclado, e busca.js/duplicatas.js/
   estatisticas.js/dialogos.js continuam só lendo window.TP_INDICE
   sem qualquer alteração. Ver ESTRUTURA-DO-PROJETO.md, §7-i.
   ---------------------------------------------------------------- */
(function () {
  "use strict";
  var extra = [];
  try {
    var bruto = window.localStorage ? window.localStorage.getItem("tp:indice-local") : null;
    if (bruto) extra = JSON.parse(bruto) || [];
  } catch (erro) {
    extra = [];
  }
  if (!extra.length) return;
  var porSlug = {};
  window.TP_INDICE.forEach(function (item, i) { porSlug[item.slug] = i; });
  extra.forEach(function (item) {
    if (!item || !item.slug) return;
    if (porSlug.hasOwnProperty(item.slug)) window.TP_INDICE[porSlug[item.slug]] = item;
    else { window.TP_INDICE.push(item); porSlug[item.slug] = window.TP_INDICE.length - 1; }
  });
})();
